### ISSUE TITLE
Issue with 1976 Records

### ISSUE THREAD

**Issue by gleporeNARA** [jtfrey/nara-to-yaml#1]
I'm getting the below errors when trying to read the 1976 Survey Data File. Any suggestions?

The file was download from:

https://catalog.archives.gov/id/1501572

nara-to-yaml RG441.ESS.CVRGY76
ERROR:  unable to read record
ERROR:  unable to read record
ERROR:  unknown record type at 49631
ERROR:  unable to read record
ERROR:  end of secondary records extends beyond primary record bounds

nara-to-yaml --output=csv:district.csv:school.csv:classroom.csv: RG441.ESS.CVRGY76 
ERROR:  unable to read record
ERROR:  unable to read record
ERROR:  unknown record type at 49631
ERROR:  unable to read record
ERROR:  end of secondary records extends beyond primary record bounds

**Comment by jtfrey** [comment]
The program must be compiled specifically to use the 1976 or pre-1976 data format; pre-1976 is the default.  Tell CMake to configure for 1976 format:

```
ccmake -DNARA_1976_FORMAT=TRUE [...]
```

**Comment by jtfrey** [comment]
Updated README.md with info re: building to handle the 1976 data format versus the pre-1976 format.

**Comment by gleporeNARA** [comment]
Thanks - one other question, the readme states "Prior to 1972 the files did not include classroom records, so that file would be empty. " However, when I ran the code against the 1976 file, it produced a zero byte classroom file. Is that correct?

**Comment by jtfrey** [comment]
The file does not appear to contain classroom records.  The documentation states:

> There are two record types in the file. The first is a district record which contains both the data from the OS/CR Form 101 and the associated error flags. The second is a school record. The school record contains the data from the OS/CR Form 101 for the district in which the school is a part, the data from the OS/CR Form 102, and the associated error flags.

I don't recall everything I had to read regarding the data formats, but I think the 1976 format does not include classroom records, and classroom records were an addition to the pre-1976 data format that showed up in 1972.
